language: ruby
rvm:
    - 2.0.0
install: gem install bundler && bundle install
script: JEKYLL_ENV=production bundle exec jekyll build
after_success: bundle exec s3_website push
branches:
    only:
        - master
