language: ruby
rvm:
- 2.0.0
install: gem install bundler && bundle install
script: JEKYLL_ENV=production bundle exec jekyll build
after_success: test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bundle exec s3_website push
branches:
  only:
  - master
notifications:
  slack:
    secure: r6M1e3HiCdqg/q6/8Nii2Ca0LwsTGnSQ2H0OX5/ESziO9IQvJcN1Tpbkde48YY7AovuBu1B5B92juCv5x+FeB3f7VK5876dQb0tXGZmVzxBgvzCTlJSo6TMy6dIIjH4AyodqxiJ3/efTt7z5S6LBwOxDFNwepvd4mQ/+CcAP/Rt9mNJ7avAloYHHm2Hzu8IDTAM+DjrLopaxnGfmNCF0ChQSuZdcB8/oSocD9FgewEOAPMf/6cDmNkEBqixzcvyD4/qHX+KLJo2FdQi2YNWsK86I9ETWNGGe2Iev7gnWrGPLa/diqanMlA0ILMxNVqCq29XvkkHMG38anvYH/G7ZAN2xHdXESCIwGgC60sYaGkWw+vEqsvEYOF2ocX3VQHF1Quge8FNsvFftbCAQlpA+zEQpZMZiTzmUCIgNa1tUzjr+fXOaRtqWPLR6InsOzRtnOn22NAZ53TEigWV/8ggtHAhyTQYEvUl2Z8e/PQV7E8Ihmz1ElQfurmDgWY8DxfEKIyzw0COGb18bIjCPaMIvIqS+ZvARHH4C8nihdXLm1879Q2GJOBbbkiF6udIZS1q0p/QcLx1r0d1bTtOP0/oxnAljUHOXXtsnrOWWKPOtI2LkQpHXoIXdxb7wmJwqLU7BZZ+NLawY64aCbsMxMTRpH0Y1ya7MDNiB7twCajUpSdc=
